### ISSUE TITLE
attention mechanism in the ensemble transformer

### ISSUE THREAD

**Issue by mishooax** [tobifinn/ensemble_transformer#7]
Hi Tobias @tobifinn - I'm trying to understand your implementation of the ensemble attention mechanism. If I'm not mistaken, `EnsConv2D` flattens the leading tensor dimensions `(bs, ens)` then the `SelfAttentionModule` attends to the (partially) flattened tensor with shape `(bs * ens, n_channels, h, w)`? The paper seems to indicate that `K`, `w_i` etc. are all dependent on the ensemble dimension - which would seem to preclude the use of a different ensemble size during inference. The code suggests otherwise, though.

**Comment by tobifinn** [comment]
Hi, the ensemble wrapper (`EnsConv2D` = ensemble wrapper + Conv2D) is used for PyTorch modules to flatten the ensemble dimension into the batch dimension. After applying the module, the dimensions are again split up into batch and ensemble. This has only technical reasons as PyTorch demands specific shapes for specific convolutions. The `SelfAttentionModule` thus attends to `(bs, ens, n_channels, h, w)`. The sizes of `K`, `w_i ` etc. depend on the size of the ensemble. `K` has size `(bs, ens, ens)`. `w_i` are the weights for the `i`-th ensemble member and has size `(bs, ens)`. As a consequence, the network is independent from the ensemble size, except that a lower ensemble size means increased noise during training. I hope that helped :)

**Comment by mishooax** [comment]
Thanks. I think I'm starting to get the idea, but please bear w/ me as I try to unpack all of this. My question was: `K`, `w_i` etc. are all dependent on the ensemble size, then how can we run inference using a _smaller_ ensemble? Won't there be a shape mismatch between, say, `K[bs, ens_training, ens_training]` and `K[bs, ens_inference, ens_inference]`? I know this isn't a problem b/c i was able to run inference with a smaller input ensemble. I'm guessing the reason is that `K` and `w_i` etc. aren't themselves learnt during training, but rather they are the outputs of ensemble-size-agnostic nnet modules? e.g. `K` is the output of `_construct_branch_layer`: https://github.com/tobifinn/ensemble_transformer/blob/9b31f193048a31efd6aacb759e8a8b4a28734e6c/ens_transformer/models/transformer_net.py#L52

Is this correct?

**Comment by tobifinn** [comment]
Yes, `K` is not the direct output of the neural network. `K` is build on the basis of the query/key. The query/key are outputs of two branch layers that are constructed with `_construct_branch_layer`. You basically not train `K` directly but rather the branch layers to get query and key. The `K` matrix is then in some sense the kernel matrix, then used to estimate the weights. As the query and key are ensemble-size agnostic, the `K` matrix as product of query and key is also ensemble-size agnostic. I hope that helped :)

**Comment by mishooax** [comment]
That makes sense - thanks!
